name: CI/CD Pipeline for Calories Burnt Prediction App

on:
  push:
    branches:
      - main  
jobs:
  build-test-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Install Dependencies
      run: |
        pip install -r requirements.txt
        pip install pytest

    - name: Run Tests
      run: |
        pytest tests/

    - name: Log in to DockerHub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build Docker Image (no cache)
      run: |
        docker build --no-cache -t ${{ secrets.DOCKER_USERNAME }}/calories-burnt-app:latest .

    - name: Push Docker Image
      run: |
        docker push ${{ secrets.DOCKER_USERNAME }}/calories-burnt-app:latest

    - name: Deploy to EC2
      uses: appleboy/ssh-action@v0.1.8
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USER }}
        key: ${{ secrets.EC2_SSH_KEY }}
        script: |
          docker pull --quiet ${{ secrets.DOCKER_USERNAME }}/calories-burnt-app:latest
          docker stop calories-burnt-app || true
          docker rm calories-burnt-app || true
          docker rmi ${{ secrets.DOCKER_USERNAME }}/calories-burnt-app:latest || true
          docker pull ${{ secrets.DOCKER_USERNAME }}/calories-burnt-app:latest
          docker run -d --name calories-burnt-app -p 8080:8501 ${{ secrets.DOCKER_USERNAME }}/calories-burnt-app:latest
